//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int DonorPersonID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual DCPersonnel DCPersonnel { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
