//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationForm
    {
        public int DonationFormID { get; set; }
        public string TravelStatus { get; set; }
        public int DCPersonnelID { get; set; }
        public int DonorID { get; set; }
        public int Weight { get; set; }
        public short Pulse { get; set; }
        public decimal SystolicBloodPressure { get; set; }
        public decimal DiastolicBloodPressure { get; set; }
        public string PastSurgeries { get; set; }
    
        public virtual DCPersonnel DCPersonnel { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
