//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WomenInfo
    {
        public int WomenInfoID { get; set; }
        public bool IsPregnant { get; set; }
        public bool PostBirth { get; set; }
        public bool Menstruating { get; set; }
    }
}
