//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GenderID { get; set; }
        public string Nin { get; set; }
        public string PhoneNo { get; set; }
        public int AddressID { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Address Address { get; set; }
    }
}
