//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivus.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public bool IsOwner { get; set; }
        public bool Active { get; set; }
        public int PersonID { get; set; }
        public int Account_AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Person Person { get; set; }
    }
}
