//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivus.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodContainer
    {
        public int BloodContainerID { get; set; }
        public System.DateTime HarvestDate { get; set; }
        public int RhID { get; set; }
        public string ContainerCode { get; set; }
        public int ContainerTypeID { get; set; }
        public int DonationCenterID { get; set; }
        public Nullable<int> BloodRequestID { get; set; }
        public int BloodTypeID { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual RH RH { get; set; }
        public virtual BloodRequest BloodRequest { get; set; }
        public virtual BloodContainerType BloodContainerType { get; set; }
        public virtual DonationCenter DonationCenter { get; set; }
    }
}
