//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivus.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationForm
    {
        public int DonationFormID { get; set; }
        public Nullable<int> DCPersonnelID { get; set; }
        public int DonorID { get; set; }
        public int Weight { get; set; }
        public int HeartRate { get; set; }
        public Nullable<int> SystolicBloodPressure { get; set; }
        public Nullable<int> DiastolicBloodPressure { get; set; }
        public string PastSurgeries { get; set; }
        public string TravelStatus { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public Nullable<bool> DonationStatus { get; set; }
        public Nullable<int> DonationCenterID { get; set; }
    
        public virtual DCPersonnel DCPersonnel { get; set; }
        public virtual DonationCenter DonationCenter { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
