//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivus.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VivusEntities : DbContext
    {
        public VivusEntities()
            : base("name=VivusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<BloodContainer> BloodContainers { get; set; }
        public virtual DbSet<BloodContainerType> BloodContainerTypes { get; set; }
        public virtual DbSet<BloodRequest> BloodRequests { get; set; }
        public virtual DbSet<BloodType> BloodTypes { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<DCPersonnel> DCPersonnels { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DonationCenter> DonationCenters { get; set; }
        public virtual DbSet<DonationForm> DonationForms { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PersonStatus> PersonStatuses { get; set; }
        public virtual DbSet<RequestPriority> RequestPriorities { get; set; }
        public virtual DbSet<RH> RHs { get; set; }
    }
}
